apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: main-config
  namespace: default
spec:
  host: a83fd17ff76904f1cb80c9e28dcd8c04-634312345.ap-south-1.elb.amazonaws.com
  #  - name: jenkins-stream
  #    service: access-ui-jenkins
  #    port: 80
  routes:
  - path: /jenkins
    route: jenkins/jenkins-vsroute
  - path: /argocd
    route: argo/argocd-vsroute

